### ISSUE TITLE
Possibility of changing the output folder

### ISSUE THREAD

**Issue by andreasjhagen** [larryprice/sass-docker#1]
I can set the scss input folder but there is no way to change the output folder. Is it possible to add an option for that?

**Comment by Noumcreation** [comment]
Would be nice yeah ! Looking for the same option :)

**Comment by Noumcreation** [comment]
I finally found a solution to change "--watch" configuration. 
You need to override the entrypoint commands **--entrypoint** option : 
`docker --rm --entrypoint sass -v $(pwd):/src larryprice/sass`

Then you can add --watch (and other) sass options :
`docker --rm --entrypoint sass= -v $(pwd):/src larryprice/sass --watch /src/inputDir:/src/outputDir`
_Note that you have to start with **"/src/"** which is the base directory on docker instance._

**Comment by andreasjhagen** [comment]
A bit of a workaround but it solves the problem perfectly. Thanks you!
